// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxdoO-0J83ShdOHz2zfITZuFv1DQeGdM',
    appId: '1:785012229258:android:291d9db2c0d9227f51d973',
    messagingSenderId: '785012229258',
    projectId: 'superando-limites-26cfd',
    storageBucket: 'superando-limites-26cfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxiH6rStCd5pezfXCFTQ3YDPv8PaDaqA',
    appId: '1:785012229258:ios:d1f01c3d0c736d1151d973',
    messagingSenderId: '785012229258',
    projectId: 'superando-limites-26cfd',
    storageBucket: 'superando-limites-26cfd.firebasestorage.app',
    iosClientId: '785012229258-5l8hspvp2qulfuei15nks21behjn53p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChgQBL69catZmJbE-Ou2NRtsb1yxr35o',
    appId: '1:785012229258:web:3f6ee41ce4fa480151d973',
    messagingSenderId: '785012229258',
    projectId: 'superando-limites-26cfd',
    authDomain: 'superando-limites-26cfd.firebaseapp.com',
    storageBucket: 'superando-limites-26cfd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxiH6rStCd5pezfXCFTQ3YDPv8PaDaqA',
    appId: '1:785012229258:ios:d1f01c3d0c736d1151d973',
    messagingSenderId: '785012229258',
    projectId: 'superando-limites-26cfd',
    storageBucket: 'superando-limites-26cfd.firebasestorage.app',
    iosClientId: '785012229258-5l8hspvp2qulfuei15nks21behjn53p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCChgQBL69catZmJbE-Ou2NRtsb1yxr35o',
    appId: '1:785012229258:web:2341c5b24329b9ed51d973',
    messagingSenderId: '785012229258',
    projectId: 'superando-limites-26cfd',
    authDomain: 'superando-limites-26cfd.firebaseapp.com',
    storageBucket: 'superando-limites-26cfd.firebasestorage.app',
  );

}