//------------------------- Bibliotecas externas -------------------------

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:auto_size_text/auto_size_text.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_masked_text2/flutter_masked_text2.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:mask_text_input_formatter/mask_text_input_formatter.dart';
import 'package:path_provider/path_provider.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:pix_flutter/pix_flutter.dart';
import 'package:provider/provider.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
//------------------------- Controladores e Serviços -------------------------
import 'package:superando_limites/controllers/env_controllers.dart';
//------------------------- Modelos -------------------------
import 'package:superando_limites/models/campo_personalizado_model.dart';
import 'package:superando_limites/models/dados_bancarios_model.dart';
import 'package:superando_limites/models/dados_estatisticos_usuarios_model.dart';
import 'package:superando_limites/models/duvida_evento_model.dart';
import 'package:superando_limites/models/endereco_model.dart';
import 'package:superando_limites/models/evento_model.dart';
import 'package:superando_limites/models/feed_noticias_model.dart';
import 'package:superando_limites/models/grupo_model.dart';
import 'package:superando_limites/models/inscricao_evento_model.dart';
import 'package:superando_limites/models/opcao_campo_model.dart';
import 'package:superando_limites/models/pagamento_inscricao_model.dart';
import 'package:superando_limites/models/premiacao_model.dart';
import 'package:superando_limites/models/resp_campo_personalizado_evento_model.dart';
import 'package:superando_limites/models/status_dados_estatisticos_model.dart';
import 'package:superando_limites/models/status_pagamento_model.dart';
import 'package:superando_limites/models/tipo_campo_model.dart';
import 'package:superando_limites/models/usuario_model.dart';
import 'package:superando_limites/services/env_services.dart';
import 'package:tab_container/tab_container.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

import '../models/depoimento_model.dart';
import '../models/resp_duvida_evento_model.dart';

//------------------------- Outros -------------------------
part '../api_banco_bacen.dart';
part '../banco_cache.dart';
//------------------------- Utilidades -------------------------
part '../utils/mascaras.dart';
part '../utils/mascaravalor.dart';
part '../utils/semana.dart';
part '../utils/validacoes.dart';
part 'pages/adm/admin_cadastrar_km_page.dart';
part 'pages/adm/cadastrar_campo_personalizado_page.dart';
part 'pages/adm/cadastrar_dados_bancarios_page.dart';
part 'pages/adm/cadastrar_depoimentos_page.dart';
part 'pages/adm/cadastrar_evento_page.dart';
part 'pages/adm/cadastrar_grupo_page.dart';
part 'pages/adm/cadastrar_noticias_page.dart';
part 'pages/adm/cadastrar_premiacao_page.dart';
part 'pages/adm/cadastrar_usuario_page.dart';
part 'pages/adm/campo_personalizado_page.dart';
part 'pages/adm/contato_adm_page.dart';
part 'pages/adm/contato_page_admin.dart';
part 'pages/adm/dados_adicionais_page_admin.dart';
part 'pages/adm/dados_adicionais_user_select_page.dart';
part 'pages/adm/dados_cadastrais_page.dart';
part 'pages/adm/detalhe_status_page.dart';
part 'pages/adm/detalhes_pagamento_page.dart';
part 'pages/adm/gestao_estatistico_page.dart';
part 'pages/adm/gestao_evento_page.dart';
part 'pages/adm/gestao_grupo_page.dart';
part 'pages/adm/gestao_noticias_page.dart';
part 'pages/adm/gestao_pagamento_page.dart';
part 'pages/adm/gestao_premiacao_page.dart';
//------------------------- Páginas -------------------------
part 'pages/adm/gestao_quilometragem_page.dart';
part 'pages/adm/gestao_usuario_page.dart';
part 'pages/adm/home_page_adm.dart';
part 'pages/adm/info_pessoais_page_admin.dart';
part 'pages/adm/info_pessoais_user_select_page.dart';
part 'pages/adm/notificacao_admin_page.dart';
part 'pages/adm/perfil_page_admin.dart';
part 'pages/adm/relatorio_geral_page.dart';
part 'pages/adm/relatorio_page.dart';
part 'pages/adm/resp_duvidas_evento_page.dart';
part 'pages/adm/status_aprovacao_km_page.dart';
part 'pages/user/screen/acompanhar_dados_page.dart';
part 'pages/user/screen/cadastrar_usuario_page.dart';
part 'pages/user/screen/cadastro_realizado_page.dart';
part 'pages/user/screen/compartilhar_meta_concluida_page.dart';
part 'pages/user/screen/contato_page_user.dart';
part 'pages/user/screen/dados_adicionais_page_user.dart';
part 'pages/user/screen/desempenho_page.dart';
part 'pages/user/screen/duvidas_evento_page.dart';
part 'pages/user/screen/enviar_dados_page.dart';

part 'pages/user/screen/info_pessoais_page_user.dart';
part 'pages/user/screen/inscricao_evento_page.dart';
part 'pages/user/screen/meu_desafio_page.dart';
part 'pages/user/screen/meus_desafios_page.dart';
part 'pages/user/screen/minha_inscricao_page.dart';
part 'pages/user/screen/noticias_page.dart';
part 'pages/user/screen/notificacao_page.dart';
part 'pages/user/screen/pagamento_evento_page.dart';
part 'pages/user/screen/perfil_page_user.dart';
part 'pages/user/screen/privacidade_e_uso_conta_page.dart';
part 'pages/user/screen/recuperar_conta_page.dart';
part 'pages/user/screen/recuperar_enviado_page.dart';
part 'pages/user/screen/sobre_app_page.dart';
part 'pages/user/screen/splash_page.dart';
part 'pages/user/screen/status_dados_enviado_page.dart';
part 'pages/user/screen/termos_de_uso_page.dart';
part 'pages/user/screen/tipo_login_page.dart';
part 'widgets/custom_button_cadastrar.dart';
part 'widgets/custom_button_compartilhar.dart';
part 'widgets/custom_button_criar_conta.dart';
part 'widgets/custom_button_duvida.dart';
part 'widgets/custom_button_ja_tenho_conta.dart';
part 'widgets/custom_button_resp_duvida.dart';
part 'widgets/custom_button_salvar.dart';
part 'widgets/custom_button_voltar.dart';
part 'widgets/custom_dropdown.dart';
part 'widgets/custom_dropdown_ano.dart';
part 'widgets/custom_dropdown_grupo.dart';
part 'widgets/custom_dropdown_grupo_cadastro.dart';
part 'widgets/custom_dropdown_premiacao.dart';
part 'widgets/custom_navigation_bar.dart';
//------------------------- Widgets personalizados -------------------------
part 'widgets/custom_navigation_bar_adm.dart';
part 'widgets/custom_semicirculo_admin.dart';
part 'widgets/custom_semicirculo_perfil.dart';
part 'widgets/custom_termos_de_uso.dart';
part 'widgets/motivo_rejeicao_overlay.dart';
part 'widgets/salvando_snackbar.dart';
part 'widgets/salvo_sucesso_snackbar.dart';

//________________________homepage________________
part 'pages/user/home_page/home_page.dart';
part 'pages/user/home_page/home_page_state.dart';
part 'pages/user/home_page/components/news_section.dart';
part 'pages/user/home_page/components/filters_section..dart';
part 'pages/user/home_page/components/challenge_section..dart';
part 'pages/user/home_page/components/instantaneo_section.dart';
part 'pages/user/home_page/components/depoimentos_section.dart';
